anand-p-r/fmi-hass-custom

- sensor.py
replaced unit_percentage with percentage based on breaking changes in hassio 0.115
> Fix breaking changes from HomeAssistant 0.115

- README.md
- __init__.py
- config_flow.py
- const.py
- manifest.json
- sensor.py
- strings.json
- translations/en.json
- weather.py
Weather and custom sensor can be configured and updated via UI.
> Updated with HASS config_flow guidelines

- LICENSE
- README.md
- __init__.py
- const.py
- manifest.json
- sensor.py
- State contains current sea level height in cm.
- Attribute contains the time corresponding to current state
- Attributes also contains list of forecast data
- Specific values in time can be extracted using template sensors
> Updates to sea level sensor

- __init__.py
- sensor.py
> Bug: Index out of range

- manifest.json
- sensor.py
- Index out of range handling.
- Additional debug logs.
> Merge fixes for sea level sensor

- __init__.py
- manifest.json
> Bug fix - index check

- __init__.py
- manifest.json
- sensor.py
Avoid using local variable from init to periodically refresh sensor data.
> Use coordinator to refresh data

- __init__.py
- config_flow.py
- const.py
- manifest.json
- sensor.py
- test.py
- utils.py
- weather.py
- Introduce bounding box for a lat/long to 2500kms half distance.
- Introduce timeouts for URLs
- Move utilities to .... well utils.py
- Added iot_class
- Added more debug prints
- Increased async timeout values, although this is not necessary for now.
> Fix amount of records pulled for lightning data

- __init__.py
- const.py
- manifest.json
- test.py
- utils.py
- Lat and Long are reversed when CRS:EPSG::4258 is used for bounding box coordinates.
- Increased async timeout to 40secs - just in case.
> Bouding box issue

- const.py
- manifest.json
- test.py
> Fixed num days to pull lightning data

- __init__.py
- config_flow.py
- const.py
- strings.json
- translations/en.json
- weather.py
In this mode, forecast is aggregated to get high and low day temperatre
Example of dashboard card:
Configuration options:
> Add 'daily mode' option.

- README.md
- __init__.py
- config_flow.py
- const.py
- manifest.json
- strings.json
- translations/en.json
- weather.py
- Update feature added by [@tdragon](https://github.com/anand-p-r/fmi-hass-custom/pull/36).
- Updated README.
> Add Daily Mode to FMI integration

- manifest.json
- sensor.py
- translations/en-GB.json
- Refresh was pulling from incorrect variable.
> fixed lightning update problem

- README.md
- manifest.json
- sensor.py
- utils.py
#44 
Updated the installation instructions with more information
#45 
Updated to check for daylight hours (between sunrise and sunset), instead of only sunset.
#46 
https://github.com/home-assistant/core/pull/47304
> Fixes for multiple issues

- manifest.json
- weather.py
Compatible with weather template.
> Time format in forecast

- weather.py
> Change Home Assistant's depracated forecast property.

- sensor.py
> Add measurement state_class property and clean up sensor code.

- __init__.py
- sensor.py
- weather.py
> Fix sensor unique_id and code cleanup

- __init__.py
- sensor.py
- weather.py
Sensors are updated when new data is received now. Unnecessary polling disable.
Some other cleanups and error handling enhancements.
Tested with HA 2025.7.2 and latest dev
> Sensors: disable polling

- weather.py
> weather: fix forecast values if value is not defined
